### ISSUE TITLE
Checklist 29/01

### ISSUE THREAD

**Issue by LauraJimenezH** [MarinaRH/cardify#4]
- [x] Investigar como funciona un plugin
- [x] Investigar que es $.fn
- [x] Investigar hover en mobile

**Comment by MarinaRH** [comment]
- [ ] Como Eportar e importar la función.
